version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: local
        working_dir: /usr/share/nginx/html
        networks:
            - app-network
        ports:
            - 8001:80
        volumes:
            - ./:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        env_file: ./.env
        depends_on:
            - mysql
            - redis
    mysql:
        image: "mysql:8.0"
        container_name: mysql
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "mysql_data:/var/lib/mysql"
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: "redis:alpine"
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - "appredis:/data"
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    app-network:
        driver: bridge
volumes:
    mysql_data:
        driver: local
    appredis:
        driver: local
